name: hello world

on:
  push:
    branches:
      - master

jobs:
  Hello:
    runs-on: ubuntu-18.04
    steps:
      - name: Hello World! Step
        run: echo "Hello World"
      - name: "Set up Go 1.14"
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: "Check out source code"
        uses: actions/checkout@v2
      - name: "Lint Go Code"
        uses: golangci/golangci-lint-action@v1
        with:
            version: v1.30


